services:

  db:
    image: postgres:latest
    container_name: postgres_my_chat_app
    environment:
      POSTGRES_USER: ${POSTGES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/liib/postgressql/data

volumes:
  postgres_data:


